"""Great Tables output — Publication-quality tables for XML Parser reports.

Uses great-tables (GT) to generate styled HTML tables that can be:
- Displayed in browser (interactive review)
- Exported as PNG images (embed in decks/emails)
- Fed into WeasyPrint for PDF generation (Phase 2)

PwC brand palette applied throughout.
"""

from pathlib import Path
from datetime import datetime

import pandas as pd
from great_tables import GT, style, loc, md, html, system_fonts
from great_tables import vals

from lab.xml_parser.reports import RolloverReport


# PwC brand palette
PWC_ORANGE = "#D04A02"
PWC_ORANGE_LIGHT = "#F2E6DC"
PWC_BLACK = "#000000"
PWC_WHITE = "#FFFFFF"
PWC_GREY_LIGHT = "#F5F5F5"
PWC_GREY_MED = "#E0E0E0"
PWC_GREY_DARK = "#646464"
PWC_GREEN = "#1B7340"
PWC_GREEN_LIGHT = "#E8F5E9"
PWC_RED = "#C81E1E"
PWC_RED_LIGHT = "#FFEBEE"
PWC_YELLOW = "#FFB81C"
PWC_YELLOW_LIGHT = "#FFF8E1"


def _report_to_df(report: RolloverReport, include_pass: bool = False) -> pd.DataFrame:
    """Convert RolloverReport to DataFrame for GT."""
    records = []
    for item in report.items:
        if not include_pass and item.passes:
            continue
        records.append({
            "entity": item.entity_name,
            "ref_id": item.reference_id,
            "line": item.line,
            "description": item.field_description,
            "py_value": item.py_value if item.py_value is not None else 0,
            "cy_value": item.cy_value if item.cy_value is not None else 0,
            "difference": item.difference if item.difference != 0 else 0,
            "status": "PASS" if item.passes else "FAIL",
        })
    return pd.DataFrame(records) if records else pd.DataFrame()


def gt_summary_table(reports: dict, client_name: str = "", tax_year: str = "") -> GT:
    """Generate a GT summary table for all reports."""
    records = []
    for name, report in reports.items():
        pct = round(report.passed / max(report.total_checks, 1) * 100, 1)
        records.append({
            "report": name,
            "checks": report.total_checks,
            "passed": report.passed,
            "failed": report.failed,
            "pass_rate": pct / 100,
            "status": "CLEAN" if report.failed == 0 else f"{report.failed} issues",
        })

    df = pd.DataFrame(records)

    total_checks = sum(r.total_checks for r in reports.values())
    total_pass = sum(r.passed for r in reports.values())
    total_fail = sum(r.failed for r in reports.values())

    title_text = "XML Rollover Review"
    subtitle_parts = []
    if client_name:
        subtitle_parts.append(client_name)
    if tax_year:
        subtitle_parts.append(f"TY{tax_year}")
    subtitle_parts.append(datetime.now().strftime("%B %d, %Y"))

    gt_tbl = (
        GT(df)
        .tab_header(
            title=md(f"**{title_text}**"),
            subtitle=" | ".join(subtitle_parts),
        )
        .tab_source_note(
            source_note=f"Total: {total_pass:,}/{total_checks:,} checks passed | {total_fail:,} failures"
        )
        .tab_source_note(
            source_note="Generated by Project Mythos | PwC US Tax LLP | Confidential"
        )
        .cols_label(
            report="Report",
            checks="Checks",
            passed="Pass",
            failed="Fail",
            pass_rate="Rate",
            status="Status",
        )
        .fmt_number(columns="checks", decimals=0, use_seps=True)
        .fmt_number(columns="passed", decimals=0, use_seps=True)
        .fmt_number(columns="failed", decimals=0, use_seps=True)
        .fmt_percent(columns="pass_rate", decimals=1)
        .cols_align(align="center", columns=["checks", "passed", "failed", "pass_rate", "status"])
        .cols_align(align="left", columns=["report"])
        .cols_width(
            report="200px",
            checks="80px",
            passed="80px",
            failed="80px",
            pass_rate="90px",
            status="120px",
        )
        .tab_style(
            style=style.fill(color=PWC_ORANGE),
            locations=loc.column_labels(),
        )
        .tab_style(
            style=style.text(color=PWC_WHITE, weight="bold"),
            locations=loc.column_labels(),
        )
        .tab_style(
            style=style.text(color=PWC_ORANGE, weight="bold", size="18px"),
            locations=loc.title(),
        )
        .tab_style(
            style=style.text(color=PWC_GREY_DARK, size="11px"),
            locations=loc.subtitle(),
        )
        .tab_style(
            style=style.borders(sides="bottom", color=PWC_ORANGE, weight="2px"),
            locations=loc.column_labels(),
        )
        .data_color(
            columns="pass_rate",
            palette=[PWC_RED_LIGHT, PWC_YELLOW_LIGHT, PWC_GREEN_LIGHT],
            domain=[0, 1],
        )
    )

    # Color the status column based on content
    for i, row in df.iterrows():
        if row["failed"] == 0:
            gt_tbl = gt_tbl.tab_style(
                style=[style.text(color=PWC_GREEN, weight="bold")],
                locations=loc.body(columns="status", rows=[i]),
            )
        else:
            gt_tbl = gt_tbl.tab_style(
                style=[style.text(color=PWC_RED, weight="bold")],
                locations=loc.body(columns="status", rows=[i]),
            )

    # Style failed column — highlight non-zero
    for i, row in df.iterrows():
        if row["failed"] > 0:
            gt_tbl = gt_tbl.tab_style(
                style=[style.text(color=PWC_RED, weight="bold"), style.fill(color=PWC_RED_LIGHT)],
                locations=loc.body(columns="failed", rows=[i]),
            )

    return gt_tbl


def gt_detail_table(report: RolloverReport, title: str = "", include_pass: bool = False) -> GT:
    """Generate a GT detail table for a single report."""
    df = _report_to_df(report, include_pass=include_pass)
    if df.empty:
        return None

    gt_tbl = (
        GT(df)
        .tab_header(
            title=md(f"**{title}**") if title else None,
            subtitle=report.summary if hasattr(report, "summary") else None,
        )
        .tab_source_note(
            source_note=f"{report.passed}/{report.total_checks} pass | {report.failed} failures | {len(report.entities_with_issues)} entities affected"
        )
        .cols_label(
            entity="Entity",
            ref_id="Ref ID",
            line="Line",
            description="Description",
            py_value="PY Value",
            cy_value="CY Value",
            difference="Difference",
            status="Status",
        )
        .cols_align(align="right", columns=["py_value", "cy_value", "difference"])
        .cols_align(align="center", columns=["ref_id", "line", "status"])
        .cols_align(align="left", columns=["entity", "description"])
        .cols_width(
            entity="180px",
            ref_id="70px",
            line="50px",
            description="180px",
            py_value="110px",
            cy_value="110px",
            difference="100px",
            status="70px",
        )
        .tab_style(
            style=style.fill(color=PWC_ORANGE),
            locations=loc.column_labels(),
        )
        .tab_style(
            style=style.text(color=PWC_WHITE, weight="bold", size="10px"),
            locations=loc.column_labels(),
        )
        .tab_style(
            style=style.text(color=PWC_ORANGE, weight="bold", size="14px"),
            locations=loc.title(),
        )
        .tab_style(
            style=style.text(size="9px"),
            locations=loc.body(),
        )
    )

    # Color PASS/FAIL badges
    for i, row in df.iterrows():
        if row["status"] == "PASS":
            gt_tbl = gt_tbl.tab_style(
                style=[style.text(color=PWC_GREEN, weight="bold"), style.fill(color=PWC_GREEN_LIGHT)],
                locations=loc.body(columns="status", rows=[i]),
            )
        else:
            gt_tbl = gt_tbl.tab_style(
                style=[style.text(color=PWC_RED, weight="bold"), style.fill(color=PWC_RED_LIGHT)],
                locations=loc.body(columns="status", rows=[i]),
            )

    # Highlight differences
    for i, row in df.iterrows():
        if row["difference"] != 0:
            gt_tbl = gt_tbl.tab_style(
                style=[style.text(color=PWC_RED, weight="bold")],
                locations=loc.body(columns="difference", rows=[i]),
            )

    # Alternating row colors
    for i in range(len(df)):
        if i % 2 == 1:
            gt_tbl = gt_tbl.tab_style(
                style=style.fill(color=PWC_GREY_LIGHT),
                locations=loc.body(rows=[i]),
            )

    return gt_tbl


def _save_gt_html(gt_table: GT, output_path: Path):
    """Save GT table as standalone HTML file."""
    html_content = gt_table.as_raw_html()
    wrapped = f"""<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<style>
  body {{ font-family: 'Segoe UI', system-ui, sans-serif; margin: 40px; background: #fafafa; }}
</style>
</head>
<body>
{html_content}
</body>
</html>"""
    output_path.write_text(wrapped, encoding="utf-8")


def gt_full_review(reports: dict, output_dir: str | Path, client_name: str = "", tax_year: str = ""):
    """Generate full set of GT tables and save as HTML files."""
    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    files_created = []

    # Summary table
    summary_gt = gt_summary_table(reports, client_name=client_name, tax_year=tax_year)
    summary_path = output_dir / "summary.html"
    _save_gt_html(summary_gt, summary_path)
    files_created.append(summary_path)

    # Detail tables for reports with issues
    for name, report in reports.items():
        if report.failed == 0 and "Movement" not in name and "Comparison" not in name:
            continue

        include_all = "Movement" in name or "Comparison" in name
        gt_tbl = gt_detail_table(report, title=name, include_pass=include_all)
        if gt_tbl is None:
            continue

        safe_name = name.replace(" ", "_").replace("/", "-").lower()
        detail_path = output_dir / f"detail_{safe_name}.html"
        _save_gt_html(gt_tbl, detail_path)
        files_created.append(detail_path)

    # Combined single-page report
    combined_path = output_dir / "full_report.html"
    _save_combined_html(reports, combined_path, client_name, tax_year)
    files_created.append(combined_path)

    return files_created


def _save_combined_html(reports: dict, output_path: Path, client_name: str = "", tax_year: str = ""):
    """Generate a single combined HTML with all tables (best for WeasyPrint later)."""
    parts = []
    parts.append(f"""<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<style>
  body {{ font-family: 'Segoe UI', system-ui, sans-serif; margin: 40px auto; max-width: 1100px; background: #fff; }}
  .page-break {{ page-break-before: always; margin-top: 40px; }}
  .header-bar {{ background: #D04A02; height: 6px; margin-bottom: 20px; }}
  h1 {{ color: #D04A02; margin-bottom: 4px; }}
  .subtitle {{ color: #646464; font-size: 13px; margin-bottom: 30px; }}
  .section {{ margin-top: 40px; }}
  .footer {{ margin-top: 40px; padding-top: 12px; border-top: 1px solid #ddd; color: #999; font-size: 11px; text-align: center; }}
</style>
</head>
<body>
<div class="header-bar"></div>
<h1>XML Rollover Review</h1>
<div class="subtitle">{client_name} | TY{tax_year} | {datetime.now().strftime('%B %d, %Y')}</div>
""")

    # Summary
    summary_gt = gt_summary_table(reports, client_name=client_name, tax_year=tax_year)
    parts.append(summary_gt.as_raw_html())

    # Details
    for name, report in reports.items():
        if report.failed == 0:
            continue
        gt_tbl = gt_detail_table(report, title=name, include_pass=False)
        if gt_tbl is None:
            continue
        parts.append(f'<div class="page-break section">')
        parts.append(gt_tbl.as_raw_html())
        parts.append("</div>")

    parts.append('<div class="footer">Generated by Project Mythos | PwC US Tax LLP | Confidential - For internal use only</div>')
    parts.append("</body></html>")

    output_path.write_text("\n".join(parts), encoding="utf-8")
