"""HTML Exporter — Great Tables publication-quality output.

Generates styled HTML reports using the great-tables library:
- Summary table (all reports at a glance)
- Detail tables (per-report drill-down)
- Combined single-page HTML (print-ready)
"""

from __future__ import annotations

from pathlib import Path
from datetime import datetime

import pandas as pd
from great_tables import GT, style, loc, md

from lab.xml_parser.core.models import Finding, ReviewReport, RolloverReport
from lab.xml_parser.export.design_system import DesignSystem as DS


def _report_to_df(report: RolloverReport, include_pass: bool = False) -> pd.DataFrame:
    """Convert RolloverReport to DataFrame for GT."""
    records = []
    for item in report.items:
        if not include_pass and item.passes:
            continue
        records.append({
            "entity": item.entity_name,
            "ref_id": item.reference_id,
            "line": item.line,
            "description": item.field_description,
            "py_value": item.py_value if item.py_value is not None else 0,
            "cy_value": item.cy_value if item.cy_value is not None else 0,
            "difference": item.difference if item.difference != 0 else 0,
            "status": "PASS" if item.passes else "FAIL",
        })
    return pd.DataFrame(records) if records else pd.DataFrame()


def summary_table(reports: dict[str, RolloverReport], client_name: str = "", tax_year: str = "") -> GT:
    """Generate a GT summary table showing all reports at a glance."""
    records = []
    for name, report in reports.items():
        pct = round(report.passed / max(report.total_checks, 1) * 100, 1)
        records.append({
            "report": name,
            "checks": report.total_checks,
            "passed": report.passed,
            "failed": report.failed,
            "pass_rate": pct / 100,
            "status": "CLEAN" if report.failed == 0 else f"{report.failed} issues",
        })

    df = pd.DataFrame(records)
    total_checks = sum(r.total_checks for r in reports.values())
    total_pass = sum(r.passed for r in reports.values())
    total_fail = sum(r.failed for r in reports.values())

    subtitle_parts = []
    if client_name:
        subtitle_parts.append(client_name)
    if tax_year:
        subtitle_parts.append(f"TY{tax_year}")
    subtitle_parts.append(datetime.now().strftime("%B %d, %Y"))

    gt_tbl = (
        GT(df)
        .tab_header(
            title=md("**XML Rollover Review**"),
            subtitle=" | ".join(subtitle_parts),
        )
        .tab_source_note(
            source_note=f"Total: {total_pass:,}/{total_checks:,} checks passed | {total_fail:,} failures"
        )
        .tab_source_note(
            source_note="Generated by Project Mythos"
        )
        .cols_label(
            report="Report", checks="Checks", passed="Pass",
            failed="Fail", pass_rate="Rate", status="Status",
        )
        .fmt_number(columns="checks", decimals=0, use_seps=True)
        .fmt_number(columns="passed", decimals=0, use_seps=True)
        .fmt_number(columns="failed", decimals=0, use_seps=True)
        .fmt_percent(columns="pass_rate", decimals=1)
        .cols_align(align="center", columns=["checks", "passed", "failed", "pass_rate", "status"])
        .cols_align(align="left", columns=["report"])
        .cols_width(
            report="200px", checks="80px", passed="80px",
            failed="80px", pass_rate="90px", status="120px",
        )
        .tab_style(style=style.fill(color=DS.NAVY), locations=loc.column_labels())
        .tab_style(style=style.text(color=DS.WHITE, weight="bold"), locations=loc.column_labels())
        .tab_style(style=style.text(color=DS.COPPER, weight="bold", size="18px"), locations=loc.title())
        .tab_style(style=style.text(color=DS.GRAPHITE, size="11px"), locations=loc.subtitle())
        .tab_style(style=style.borders(sides="bottom", color=DS.COPPER, weight="2px"), locations=loc.column_labels())
        .data_color(
            columns="pass_rate",
            palette=[DS.DANGER_BG, DS.WARNING_BG, DS.SUCCESS_BG],
            domain=[0, 1],
        )
    )

    for i, row in df.iterrows():
        if row["failed"] == 0:
            gt_tbl = gt_tbl.tab_style(
                style=[style.text(color=DS.SUCCESS, weight="bold")],
                locations=loc.body(columns="status", rows=[i]),
            )
        else:
            gt_tbl = gt_tbl.tab_style(
                style=[style.text(color=DS.DANGER, weight="bold")],
                locations=loc.body(columns="status", rows=[i]),
            )

    for i, row in df.iterrows():
        if row["failed"] > 0:
            gt_tbl = gt_tbl.tab_style(
                style=[style.text(color=DS.DANGER, weight="bold"), style.fill(color=DS.DANGER_BG)],
                locations=loc.body(columns="failed", rows=[i]),
            )

    return gt_tbl


def detail_table(report: RolloverReport, title: str = "", include_pass: bool = False) -> GT | None:
    """Generate a GT detail table for a single report."""
    df = _report_to_df(report, include_pass=include_pass)
    if df.empty:
        return None

    gt_tbl = (
        GT(df)
        .tab_header(
            title=md(f"**{title}**") if title else None,
            subtitle=report.summary if hasattr(report, "summary") else None,
        )
        .tab_source_note(
            source_note=f"{report.passed}/{report.total_checks} pass | {report.failed} failures | {len(report.entities_with_issues)} entities affected"
        )
        .cols_label(
            entity="Entity", ref_id="Ref ID", line="Line",
            description="Description", py_value="PY Value",
            cy_value="CY Value", difference="Difference", status="Status",
        )
        .cols_align(align="right", columns=["py_value", "cy_value", "difference"])
        .cols_align(align="center", columns=["ref_id", "line", "status"])
        .cols_align(align="left", columns=["entity", "description"])
        .cols_width(
            entity="180px", ref_id="70px", line="50px",
            description="180px", py_value="110px", cy_value="110px",
            difference="100px", status="70px",
        )
        .tab_style(style=style.fill(color=DS.NAVY), locations=loc.column_labels())
        .tab_style(style=style.text(color=DS.WHITE, weight="bold", size="10px"), locations=loc.column_labels())
        .tab_style(style=style.text(color=DS.COPPER, weight="bold", size="14px"), locations=loc.title())
        .tab_style(style=style.text(size="9px"), locations=loc.body())
    )

    for i, row in df.iterrows():
        if row["status"] == "PASS":
            gt_tbl = gt_tbl.tab_style(
                style=[style.text(color=DS.SUCCESS, weight="bold"), style.fill(color=DS.SUCCESS_BG)],
                locations=loc.body(columns="status", rows=[i]),
            )
        else:
            gt_tbl = gt_tbl.tab_style(
                style=[style.text(color=DS.DANGER, weight="bold"), style.fill(color=DS.DANGER_BG)],
                locations=loc.body(columns="status", rows=[i]),
            )

    for i, row in df.iterrows():
        if row["difference"] != 0:
            gt_tbl = gt_tbl.tab_style(
                style=[style.text(color=DS.DANGER, weight="bold")],
                locations=loc.body(columns="difference", rows=[i]),
            )

    for i in range(len(df)):
        if i % 2 == 1:
            gt_tbl = gt_tbl.tab_style(
                style=style.fill(color=DS.CLOUD),
                locations=loc.body(rows=[i]),
            )

    return gt_tbl


def _save_html(gt_table: GT, output_path: Path) -> None:
    """Save GT table as standalone HTML file."""
    html_content = gt_table.as_raw_html()
    wrapped = f"""<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<style>
  body {{ font-family: 'Segoe UI', system-ui, sans-serif; margin: 40px; background: #fafafa; }}
</style>
</head>
<body>
{html_content}
</body>
</html>"""
    output_path.write_text(wrapped, encoding="utf-8")


def findings_table(report: ReviewReport, title: str = "Review Findings") -> GT | None:
    """Generate a GT table for ReviewReport findings."""
    if not report or not report.findings:
        return None

    records = []
    for f in report.findings:
        records.append({
            "check_id": f.check_id,
            "severity": f.severity,
            "category": f.category,
            "entity": f"{f.entity_name} ({f.entity_code})",
            "description": f.description[:60],
            "delta": f.delta if f.delta else 0,
        })

    df = pd.DataFrame(records)
    severity_order = {"HIGH": 0, "MEDIUM": 1, "LOW": 2}
    df["_sort"] = df["severity"].map(severity_order)
    df = df.sort_values("_sort").drop(columns="_sort").reset_index(drop=True)

    high = sum(1 for f in report.findings if f.severity == "HIGH")
    subtitle = f"{len(report.findings)} findings | {high} HIGH | {report.entity_count} entities"

    gt_tbl = (
        GT(df)
        .tab_header(title=md(f"**{title}**"), subtitle=subtitle)
        .cols_label(
            check_id="Check", severity="Severity", category="Category",
            entity="Entity", description="Description", delta="Delta",
        )
        .cols_align(align="center", columns=["check_id", "severity"])
        .cols_align(align="right", columns=["delta"])
        .cols_width(
            check_id="70px", severity="70px", category="90px",
            entity="180px", description="220px", delta="90px",
        )
        .tab_style(style=style.fill(color=DS.NAVY), locations=loc.column_labels())
        .tab_style(style=style.text(color=DS.WHITE, weight="bold", size="10px"), locations=loc.column_labels())
        .tab_style(style=style.text(color=DS.COPPER, weight="bold", size="14px"), locations=loc.title())
        .tab_style(style=style.text(size="9px"), locations=loc.body())
    )

    for i, row in df.iterrows():
        sev = row["severity"]
        if sev == "HIGH":
            gt_tbl = gt_tbl.tab_style(
                style=[style.text(color=DS.DANGER, weight="bold"), style.fill(color=DS.DANGER_BG)],
                locations=loc.body(columns="severity", rows=[i]),
            )
        elif sev == "MEDIUM":
            gt_tbl = gt_tbl.tab_style(
                style=[style.text(color=DS.WARNING, weight="bold"), style.fill(color=DS.WARNING_BG)],
                locations=loc.body(columns="severity", rows=[i]),
            )

    for i in range(len(df)):
        if i % 2 == 1:
            gt_tbl = gt_tbl.tab_style(
                style=style.fill(color=DS.CLOUD),
                locations=loc.body(rows=[i]),
            )

    return gt_tbl


def export_html(
    reports: dict[str, RolloverReport],
    output_dir: str | Path,
    client_name: str = "",
    tax_year: str = "",
    review_report: ReviewReport | None = None,
) -> list[Path]:
    """Generate full set of GT tables and save as HTML files.

    Returns list of created file paths.
    """
    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    files_created = []

    # Findings table (if review report provided)
    if review_report and review_report.findings:
        ft = findings_table(review_report)
        if ft is not None:
            findings_path = output_dir / "findings.html"
            _save_html(ft, findings_path)
            files_created.append(findings_path)

    # Summary table
    summary_gt = summary_table(reports, client_name=client_name, tax_year=tax_year)
    summary_path = output_dir / "summary.html"
    _save_html(summary_gt, summary_path)
    files_created.append(summary_path)

    # Detail tables
    for name, report in reports.items():
        if report.failed == 0 and "Movement" not in name and "Comparison" not in name:
            continue

        include_all = "Movement" in name or "Comparison" in name
        gt_tbl = detail_table(report, title=name, include_pass=include_all)
        if gt_tbl is None:
            continue

        safe_name = name.replace(" ", "_").replace("/", "-").lower()
        detail_path = output_dir / f"detail_{safe_name}.html"
        _save_html(gt_tbl, detail_path)
        files_created.append(detail_path)

    # Combined single-page
    combined_path = output_dir / "full_report.html"
    _save_combined_html(reports, combined_path, client_name, tax_year)
    files_created.append(combined_path)

    return files_created


def _save_combined_html(
    reports: dict[str, RolloverReport],
    output_path: Path,
    client_name: str = "",
    tax_year: str = "",
) -> None:
    """Generate a single combined HTML with all tables."""
    parts = [f"""<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<style>
  body {{ font-family: 'Segoe UI', system-ui, sans-serif; margin: 40px auto; max-width: 1100px; background: #fff; }}
  .page-break {{ page-break-before: always; margin-top: 40px; }}
  .header-bar {{ background: {DS.COPPER}; height: 6px; margin-bottom: 20px; }}
  h1 {{ color: {DS.COPPER}; margin-bottom: 4px; }}
  .subtitle {{ color: {DS.GRAPHITE}; font-size: 13px; margin-bottom: 30px; }}
  .section {{ margin-top: 40px; }}
  .footer {{ margin-top: 40px; padding-top: 12px; border-top: 1px solid #ddd; color: #999; font-size: 11px; text-align: center; }}
</style>
</head>
<body>
<div class="header-bar"></div>
<h1>XML Rollover Review</h1>
<div class="subtitle">{client_name} | TY{tax_year} | {datetime.now().strftime('%B %d, %Y')}</div>
"""]

    summary_gt = summary_table(reports, client_name=client_name, tax_year=tax_year)
    parts.append(summary_gt.as_raw_html())

    for name, report in reports.items():
        if report.failed == 0:
            continue
        gt_tbl = detail_table(report, title=name, include_pass=False)
        if gt_tbl is None:
            continue
        parts.append('<div class="page-break section">')
        parts.append(gt_tbl.as_raw_html())
        parts.append("</div>")

    parts.append('<div class="footer">Generated by Project Mythos</div>')
    parts.append("</body></html>")

    output_path.write_text("\n".join(parts), encoding="utf-8")
